@startuml

skinparam packageStyle rectangle
skinparam shadowing false

@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title User Story 008 - Sequence Diagram (SD)

autonumber

actor "Agent" as User
participant ":SetCommissionUI" as UI
participant ":SetCommissionController" as CTRL
participant "CreatePropertyList" as ListEditor
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "propertyRepository\n:PropertyRepository" as PropertyRepository
'participant "Property" as Property
'participant "Request" as Request

    activate User
    User -> UI : asks to post an announcement
    activate UI

    UI -> CTRL** : create

    UI -> CTRL : getProperties()
    activate CTRL

    CTRL -> RepositorySingleton : getInstance()
    activate RepositorySingleton

    RepositorySingleton --> CTRL: repositories
    deactivate RepositorySingleton

    CTRL -> PLAT : getPropertyRepository()
    activate PLAT

    PLAT --> CTRL: propertyRepository
    deactivate PLAT

    CTRL -> PropertyRepository : getProperties()
    activate PropertyRepository

    PropertyRepository --> CTRL : propertyList
    deactivate PropertyRepository

    CTRL --> UI : propertyList
    deactivate CTRL

    UI --> User : asks if they only want to see 'for rent', 'for sale' or both
    deactivate UI

    User -> UI : answers the question
    activate UI

        alt answer isn't "both"
        UI -> CTRL : getListOfXTypeOfRequest(propertyList, type)
        activate CTRL
        CTRL -> ListEditor : getPropertiesWithXTypeOfSale(propertyList, type)
        activate ListEditor
        ListEditor -> ListEditor : create list with all the properties\nof the requested type
        ListEditor --> CTRL : propertyList
        deactivate ListEditor
        CTRL --> UI : propertyList
        deactivate CTRL
        end

    UI --> User : asks if they only want to see lands, apartments, houses or all of those
    deactivate UI

    User -> UI : answers the question
    activate UI

        alt answer isn't "all of them"
        UI -> CTRL : getListOfXTypeOfProperty(propertyList, type)
        activate CTRL
        alt answer is land
        CTRL -> ListEditor : getPropertiesIfTheyAreLand(propertyList)
        activate ListEditor
        ListEditor -> ListEditor : create list with\nall the lands
        ListEditor --> CTRL : propertyList
        deactivate ListEditor

        else answer is apartment
        CTRL -> ListEditor : getPropertiesIfTheyAreApartment(propertyList)
        activate ListEditor
        ListEditor -> ListEditor : create list with\nall the apartments
        ListEditor --> CTRL : propertyList
        deactivate ListEditor

        else answer is house
        CTRL -> ListEditor : getPropertiesIfTheyAreLand(propertyList)
        activate ListEditor
        ListEditor -> ListEditor : create list with\nall the houses
        ListEditor --> CTRL : propertyList
        deactivate ListEditor
        end
        CTRL --> UI : propertyList
        deactivate CTRL
        end

    alt there aren't any requests with the given specifications
        UI --> User : shows message saying that there aren't any\nrequests that meet the given requirements
        else there are
        UI --> User : shows all property requests to that specific agent starting from most recent
    end
    deactivate UI

@enduml