@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
'hide methods

title US008 List Property Announcement Requests - Domain Model

hide methods

class Agent {
-email
-name
-phoneNumber
-address
-store
-ccNumber
-taxNumber
-password
}

interface Property {
}

class Request{
-type
-price
-priceUnit
-isItPublished
-commissionDate
-owner
-commissionValue
-duration
}

class Land{
-area
-location
-distanceFromCityCentre
-agent
-photographs
-finalPrice
-announcementDate
-saleDate
-request
-store
}

class Apartment {
-area
-location
-distanceFromCityCentre
-agent
-numOfBedrooms
-numOfBathrooms
-numOfParkingSpaces
-centralHeating
-airConditioning
-photographs
-finalPrice
-announcementDate
-saleDate
-request
-store
}

class House {
-area
-location
-distanceFromCityCentre
-agent
-numOfBedrooms
-numOfBathrooms
-numOfParkingSpaces
-centralHeating
-airConditioning
-basement
-inhabitableLoft
-sunExposure
-photographs
-finalPrice
-announcementDate
-saleDate
-request
-store
}

class System {
-advertisements
-application
}

System --> Property : gets list of properties done\nto the agent currently using the system
Agent -> System : asks to post announcement(s), giving the\nfilters and sorting settings that they want
System -> Agent : \n\nprints sorted list of requests

System -> System : sorts and filters\nthe property list as the\nagent requested

Property -> Request : contains

Property --> Apartment : can be
Property --> House : can be
Property --> Land : can be

@enduml