@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US004 -  Sequence Diagram (SD)

autonumber

'hide footbox
actor "Owner" as ADM
participant ":SendPropertyRequestUI" as UI
participant ":SendPropertyRequestController" as CTRL
participant "manageEmployees\n:ManageEmployees" as manageEmployees
participant "manageRequests\n:ManageRequests" as manageRequests
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "requestRepository:\nRequestRepository" as RequestRepository


activate ADM

        ADM -> UI : asks to create property ad

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getAgents()
            activate CTRL

                CTRL -> manageEmployees : getEmployeeByRole(Agent)
                activate manageEmployees


                manageEmployees -> RepositorySingleton : getInstance()
                    activate RepositorySingleton

                        RepositorySingleton --> manageEmployees: repositories
                    deactivate RepositorySingleton

                    manageEmployees -> PLAT : getEmployeeRepository()
                    activate PLAT

                        PLAT --> manageEmployees: EmployeeRepository
                    deactivate PLAT

                    manageEmployees -> manageEmployees : filterByRole(Agent)

                    manageEmployees --> CTRL : listOfAgents
                deactivate manageEmployees

                CTRL --> UI : listOfAgents
            deactivate CTRL

            UI --> ADM : shows list of agents\n and asks to select one
        deactivate UI

    ADM -> UI : selects responsible agent
    activate UI

        UI --> ADM : requests data about property
    deactivate UI

    ADM -> UI : types requested data about property
    activate UI

        UI -> UI : validateData

        UI --> ADM : shows selected agent and requested data
    deactivate UI

    ADM -> UI : submits request
    activate UI

        UI -> CTRL : submitRequest(request)
        activate CTRL


                    CTRL -> manageRequests : addRequest(request)
                    activate manageRequests


                         manageRequests -> RepositorySingleton : getInstance()
                                activate RepositorySingleton

                                    RepositorySingleton --> manageRequests: repositories
                                deactivate RepositorySingleton

                                manageRequests -> PLAT : getRequestRepository()
                                activate PLAT

                                    PLAT --> manageRequests: RequestRepository
                                deactivate PLAT

                                manageRequests -> RequestRepository : addRequest(request)
                                activate RequestRepository

                                RequestRepository --> manageRequests : true/false
                                deactivate RequestRepository

                                manageRequests --> CTRL : Show operation success
                            deactivate manageRequests

          CTRL --> UI: show operation success
          deactivate CTRL
    UI --> ADM: show operation success
    deactivate UI

deactivate ADM


@enduml