@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title User Story 004 - System Sequence Diagram (SSD)

autonumber

actor "Owner" as Owner
participant ":System" as System

activate Owner

    Owner -> System : asks to submit a request for listing a property sale or rent\n(with description, informal description, technical description, cost)
    activate System

    System --> Owner : lists all available agents
    deactivate System

    Owner -> System : chooses the agent that will the responsible for that property
    activate System

    System --> Owner : asks how many property requests they want to send
    deactivate System

    Owner -> System : answers the question with number x
    activate System

    loop x times
        System --> Owner : asks for general details about request like p if it is 'for sale' (it would be in €)\nor 'for rent' (it would be in €/month) (select one of those options),\ncontract duration if it is 'for rent' and commission value (% or fixed value)
        deactivate System
        Owner -> System : provides the needed information
        activate System
        System --> Owner : asks if they want to publish a request for a land,\napartment or for a house
        deactivate System

        Owner -> System : selects one of those 3 options
        activate System
        alt answer is land
            System --> Owner : asks the land's area (in m^2), location, distance from city centre (in km)
            deactivate System
            Owner -> System : selects and types the requested information
            activate System
        else answer is apartment
            System --> Owner : asks the apartment's area (in m^2), location, distance from city centre\n(in km), number of bedrooms, bathrooms and parking spaces,\navailability of central heating and air conditioning.
            deactivate System
            Owner -> System : selects and types the requested information
            activate System
        else answer is house
            System --> Owner : asks the house's area (in m^2), location, distance from city centre\n(in km), number of bedrooms, bathrooms and parking spaces,\navailability of central heating, air conditioning,\nbasement and inhabitable loft and direction of sun exposure (N/S/E/W)
            deactivate System
            Owner -> System : selects and types the requested information
            activate System
        end
        System --> Owner : asks if the user wants to submit the given request
        deactivate System
        Owner -> System : gives their answer (Yes/No)
        activate System
        alt answer is Yes
            System --> System : registers the new\nproperty request
        end
        System --> Owner : displays operation (un)success
    end


@enduml