@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title User Story 010 - Sequence Diagram (SD)

autonumber

'hide footbox
actor "Client" as Client
participant ":PlaceOrderUI" as UI
participant ":PlaceOrderController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "propertyAnnouncementRepository:\nPropertyAnnouncementRepository" as REP
participant ":authenticationRepository:\nAuthenticationRepository" as AUTHRepository
participant "EditAndSortLists" as EAS
participant "OrderRepository" as REO



activate Client

    Client -> UI : asks to place an order
    activate UI

    UI -> CTRL** : creates
    UI -> CTRL : getProperties()
    activate CTRL

    CTRL -> RepositorySingleton : getInstance()
    activate RepositorySingleton

    RepositorySingleton --> CTRL: repositories
    deactivate RepositorySingleton

    CTRL -> PLAT : getPropertyRepository()
    activate PLAT

    PLAT --> CTRL: propertyRepository
    deactivate PLAT

    CTRL -> REP : getProperties()
    activate REP

    REP --> CTRL : propertyList
    deactivate REP

    CTRL --> UI : propertyList
    deactivate CTRL

    UI -> CTRL : getCurrentUserEmail()
    activate CTRL

    CTRL -> RepositorySingleton : getInstance()
    activate RepositorySingleton

    RepositorySingleton --> CTRL: repositories
    deactivate RepositorySingleton

    CTRL -> PLAT : getAuthenticationRepository()
    activate PLAT

    PLAT --> CTRL: authenticationRepository
    deactivate PLAT

    CTRL -> AUTHRepository : getUserSession()
    activate AUTHRepository

    AUTHRepository --> CTRL : userSession
    deactivate AUTHRepository

    CTRL --> UI : currentUserEmail
    deactivate CTRL

    UI -> CTRL : getPropertiesIfNotFromTheSameOwner(propertyList, email)
    activate CTRL

    CTRL -> EAS** : creates
    CTRL -> EAS : getPropertiesIfNotFromTheSameOwner(propertyList, email)
    activate EAS

    EAS --> CTRL : filtered list
    deactivate EAS

    CTRL --> UI : filtered list
    deactivate CTRL


    alt there are no properties in the system
        UI --> Client : tells the user that there are no properties in the system
    else there are properties in the system

        UI --> Client : request to select desired Filters to list the properties
    deactivate UI

    Client -> UI : selects the desired filters (or not)
    activate UI

    alt the user chose one or more filters
    UI -> CTRL : edit list
    activate CTRL
    CTRL -> EAS : edit list as asked
    activate EAS
    EAS --> CTRL : filtered list
    deactivate EAS
    CTRL --> UI : filtered list
    deactivate CTRL
    end

    alt there are no properties in the system that meet the chosen filters
        UI --> Client : tells the user that there are no properties in the system with those criteria
    else there are properties in the system that meet\nthose criteria or they didn't choose any criteria
        UI --> Client : list properties and request to select one
    deactivate UI

    Client -> UI : selects one property
    activate UI
    UI -> CTRL : selectProperty(propertyList, option)
    activate CTRL
    CTRL --> UI
    deactivate CTRL

    alt if the client hasn't registered an offer for this property

        UI --> Client : request the amount
    deactivate UI

    Client -> UI : sends the requested amount
    activate UI
    UI -> CTRL : requestAmount(propertyList.get(option - 1))
    activate CTRL
    CTRL --> UI
    deactivate CTRL
    UI -> CTRL : verifyAmount(amount)
    activate CTRL
    CTRL --> UI
    deactivate CTRL
    UI -> CTRL : verifyOrder(amount, email, propertyList.get(option - 1))
    activate CTRL
    CTRL --> UI : true/false
    deactivate CTRL


    alt client has sent an amount that is equal to the amount \nfrom another client for this property
            UI --> Client : displays: "An order with the same amount has already been registered \nby another client for this property"
            else otherwise
            UI -> CTRL : createAndRegisterNewOrder(amount, email, propertyList.get(option - 1))
            activate CTRL
            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getOrderRepository()
            activate PLAT

            PLAT --> CTRL: orderRepository
            deactivate PLAT

            CTRL -> REO : getOrders()
            activate REO

            REO --> CTRL : orderList
            deactivate REO

            CTRL -> REO : add(order)
            activate REO
            REO --> CTRL
            deactivate REO
            CTRL --> UI
            deactivate CTRL
        UI --> Client : displays: ""Order placed!"
        end

    else if client has already registered an offer for this property
        UI --> Client : displays: "Order already placed for this property"
        deactivate UI
        end
        end
        end

@enduml